### ISSUE TITLE
Problematic boolean flag requestingLocationUpdates

### ISSUE THREAD

**Issue by lawloretienne** [googlesamples/android-play-location#199]
I tried porting over this example of requesting location updates but it seems like there is an issue with when the requestingLocationUpdates get set.

If you look at onResume() if you dont have the location permission granted it will call requestPermissions().  This will show a system dialog, however while this has happened, onPause() was called which would have set the requestingLocationUpdates flag to false.  

Then if you select allow on the system dialog to allow the location permission then it will get into onRequestPermissionsResult() and now that its been granted it looks at the flag requestingLocationUpdates and since this is false it doesnt get inside the if block so it wont call startLocationUpdates().

Is there a way this example can be adapted to so its not buttons on a layout that start and stop location updates?

**Comment by jonndavis1993** [comment]
Change your code so that onRequestPermissionsResult() doesn't check requestingLocationUpdates flag and doesn't interfere with the location request inside of onResume(). Based on its name, the flag seems to be used to indicate location updates are in progress and thus used to stop location updates when pausing the activity. After onRequestPermissionsResult() gets called, onResume() should fire next and begin requesting updates since you have the location permission.

**Comment by lawloretienne** [comment]
Then when is the correct time to change the value of that flag?

**Comment by lawloretienne** [comment]
I figured out after many changes.  It looks like this code sample is nowhere near complete.
