### ISSUE TITLE
LocationAddress - "Address found" but no address shows

### ISSUE THREAD

**Issue by glasses618** [googlesamples/android-play-location#46]
I try the project "LocationAddress".
After I push the button "FETCH ADDRESS", "Address found" shows but no address appears.
I find the code in FetchAddressIntentService.java line129

``` java
for(int i = 0; i < address.getMaxAddressLineIndex(); i++) {
     addressFragments.add(address.getAddressLine(i));
 }
```

The value of `address.getMaxAddressLineIndex()` is 0 when there's one element in the HashMap `address.mAddressLines` [index 0: "some address line value" ], so the program didn't step into the for loop. The ArrayList `addressFragments` doesn't get the address.

**Comment by RupamShaw** [comment]
its same problem in my case too 
how to get address array size>0
what things need to set is Google map apikey also needed for locationaddress.I set it that too in manifest.even though  addresses = geocoder.getFromLocation not giving any exceptions.
in logcat.

**Comment by prasadsjoshi** [comment]
I've found that this issue seems to be phone specific -- I have a Sprint Galaxy S5 (Android 6) and I get an array length of 2, while on a Sprint Galaxy S6 (Android 6)  I get an array length of 0, and on a Sprint Galaxy S7 (Android 7) the array length is again 2 (all in the same location, and the address is identical on all 3 just split differently in the response) 

I believe a Verizon S7 (Android 7) is giving an array length of 0 as well - though it is with someone in the field so just a hypothesis. The geocoding stopped working suddenly around July 23rd or 24th on both the Sprint S6 and Verizon S7.....so something on the backend samsung services must have changed (and might be different based on provider/model)

**Comment by wakely** [comment]
Might be a semantical issue, but it seems like "max index" of 0 is correct, when there is only a single entry.  So maybe the loop range should just be switched to `i <= address.getMaxAddressLineIndex()` ?

**Comment by shailen** [comment]
I cannot repro any of this, unfortunately.
