### ISSUE TITLE
LocationUpdates sample project mRequestingLocationUpdates never true

### ISSUE THREAD

**Issue by vantose56** [googlesamples/android-play-location#79]
I downloaded the LocationUpdates project to test it on a galaxy s6, but it never gets the location. It seems to be stuck in the `onRequestPermissionResult()` method because `mRequestingLocationUpdates` is never true. Therefore it never gets to the `startLocationUpdates()` method. Again, I did not add anything to the sample, just downloaded and ran it.

Please Help

**Comment by finderAUT** [comment]
I recently did the same and found the cause!
If in onResume() mRequestingLocationUpdates && checkPermissions() is false requestPermissions() will be called although they are already granted, ending in a loop because it is auto answered and then returns to onResume() and so on.... you can fix this for example by wrapping requestPermissions() content in if(!checkPermissions()){...}

**Comment by vantose56** [comment]
Thanks so much that fixed it. But is the app supposed to display anything? The console says that all location settings are satisfied but then nothing happens.

Any suggestions? How do I get the location data?

**Comment by samtstern** [comment]
Fixed, thank you both for reporting.
